export const metadata = {
  title: "Product List",
  description: "Generated by Hemant",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
